#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------- platform ---
# Config paths diverge sharply by OS (macOS buries them in ~/Library, Linux
# follows XDG, Git Bash uses the Windows profile), so detect once up front and
# branch on OS rather than sprinkling uname checks through the script.
case "$(uname -s)" in
    Darwin)          OS=darwin ;;
    Linux)           OS=linux ;;
    MINGW*|MSYS*)    OS=windows ;;
    *) echo "unsupported platform: $(uname -s)" >&2; exit 1 ;;
esac

IS_WSL=0
if [ "$OS" = linux ] && grep -qi microsoft /proc/version 2>/dev/null; then
    IS_WSL=1
fi

XDG="${XDG_CONFIG_HOME:-$HOME/.config}"

echo "==> platform: $OS$([ "$IS_WSL" = 1 ] && echo ' (WSL)')"
echo

link() {
    local src="$1" dst="$2"
    if [ ! -e "$src" ]; then
        echo "  skip $dst (no $src)"
        return
    fi
    mkdir -p "$(dirname "$dst")"
    # Only back up real files. An existing symlink is assumed to be ours (or
    # stale) and is replaced silently; backing those up just accumulates
    # .bak symlinks pointing at whatever the previous checkout was.
    if [ -e "$dst" ] && [ ! -L "$dst" ]; then
        echo "  backing up $dst -> $dst.bak"
        mv "$dst" "$dst.bak"
    fi
    # -n is required for directories: without it, `ln -sf dir existing-symlink`
    # creates the link *inside* the target rather than replacing it.
    ln -sfn "$src" "$dst"
    echo "  linked $dst"
}

echo "==> nvim"
link "$DOTFILES/nvim" "$XDG/nvim"

echo "==> bash"
# One shared file plus a per-OS bashrc; see bash/common.sh for the split.
link "$DOTFILES/bash/common.sh" "$XDG/dotfiles/common.sh"
link "$DOTFILES/bash/bashrc.$OS" "$HOME/.bashrc"
link "$DOTFILES/bash/bash_profile.$OS" "$HOME/.bash_profile"

echo "==> git"
link "$DOTFILES/git/config" "$HOME/.gitconfig"
link "$DOTFILES/git/gitignore_global" "$HOME/.gitignore_global"

if [ "$OS" != windows ]; then
    echo "==> tmux"
    link "$DOTFILES/tmux/.tmux.conf" "$HOME/.tmux.conf"
    if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
        echo "  installing tpm..."
        git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
    fi
else
    echo "==> tmux (skipped — no tmux under Git Bash)"
fi

echo "==> ghostty"
case "$OS" in
    darwin)  link "$DOTFILES/ghostty/config.ghostty" \
                  "$HOME/Library/Application Support/com.mitchellh.ghostty/config" ;;
    linux)   link "$DOTFILES/ghostty/config.ghostty" "$XDG/ghostty/config" ;;
    windows) echo "  skipped — Ghostty is macOS/Linux only" ;;
esac

echo "==> wezterm"
if [ "$IS_WSL" = 1 ]; then
    # WezTerm is a Windows application here; its config belongs in the Windows
    # profile and is installed by install.ps1. A copy inside the WSL home would
    # never be read.
    echo "  skipped — installed on the Windows side by install.ps1"
else
    # WezTerm reads ~/.wezterm.lua on every platform, and that is the only path
    # that works unchanged from Git Bash, so use it rather than $XDG/wezterm.
    link "$DOTFILES/wezterm/wezterm.lua" "$HOME/.wezterm.lua"
fi

echo "==> kitty"
if [ "$OS" = windows ]; then
    echo "  skipped -- kitty has no Windows build"
else
    link "$DOTFILES/kitty/kitty.conf" "$XDG/kitty/kitty.conf"

    if [ "$IS_WSL" = 1 ]; then
        # Windows Start Menu integration.
        #
        # WSLg generates a shortcut for every .desktop entry that is
        # Terminal=false and NoDisplay=false -- but its scanner uses the XDG
        # default data dirs, /usr/local/share:/usr/share, because XDG_DATA_DIRS
        # is unset under WSLg. ~/.local/share/applications is NOT searched, so
        # an entry placed there is silently ignored. It has to go system-wide.
        #
        # WSLg appends " (Ubuntu)" to the name itself, so Name is just "kitty".
        KITTY_BIN="$HOME/.local/kitty.app/bin/kitty"
        if [ -x "$KITTY_BIN" ]; then
            # A wrapper rather than `env ...` directly in Exec: WSLg launches
            # this without a shell, so GALLIUM_DRIVER has to be set here or
            # Mesa falls back to llvmpipe software rendering. Keeping it in a
            # script also gives one place to add future launch environment.
            WRAPPER="$HOME/.local/bin/kitty-wsl"
            mkdir -p "$(dirname "$WRAPPER")"
            cat > "$WRAPPER" <<WRAPEOF
#!/usr/bin/env bash
# Generated by install.sh. Launches kitty with the hardware GL driver forced.
# Under WSLg, Mesa tries zink first, fails to choose a physical device, and
# silently falls back to llvmpipe -- software rendering in a GPU-accelerated
# terminal, with no error shown.
[ -e /dev/dxg ] && export GALLIUM_DRIVER=d3d12
exec "$KITTY_BIN" "\$@"
WRAPEOF
            chmod +x "$WRAPPER"
            echo "  wrote $WRAPPER"

            KITTY_ICON="$HOME/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png"
            STAGED="$XDG/kitty/kitty.desktop.staged"
            cat > "$STAGED" <<DESKTOPEOF
[Desktop Entry]
Version=1.0
Type=Application
Name=kitty
GenericName=Terminal emulator
Comment=Fast, feature-rich, GPU based terminal
TryExec=$WRAPPER
Exec=$WRAPPER
Icon=$KITTY_ICON
Categories=System;TerminalEmulator;
Terminal=false
StartupNotify=true
StartupWMClass=kitty
DESKTOPEOF

            SYS_DESKTOP=/usr/share/applications/kitty.desktop
            if cp "$STAGED" "$SYS_DESKTOP" 2>/dev/null; then
                echo "  installed $SYS_DESKTOP"
            elif sudo -n cp "$STAGED" "$SYS_DESKTOP" 2>/dev/null; then
                echo "  installed $SYS_DESKTOP (via sudo)"
            else
                echo "  NEEDS ROOT -- WSLg only reads /usr/share/applications:"
                echo "      sudo cp '$STAGED' $SYS_DESKTOP"
            fi

            # A stale entry in the user dir would shadow nothing under WSLg but
            # would duplicate the launcher on a normal Linux desktop.
            rm -f "$HOME/.local/share/applications/kitty.desktop"
        else
            echo "  kitty not installed; skipping desktop entry"
            echo "  install with: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin"
        fi

        # Machine-local kitty settings, picked up by the globinclude at the end
        # of kitty.conf. Kept out of the repo because delivery of a desktop
        # notification is machine-specific.
        #
        # wsl-notify-send.exe produces a real Windows toast -- Action Center,
        # Focus Assist and all -- rather than a Linux popup floating over the
        # desktop. kitty's own notification path speaks D-Bus, so the
        # `command` action is what routes around it.
        if command -v wsl-notify-send.exe >/dev/null 2>&1; then
            mkdir -p "$XDG/kitty/local"
            cat > "$XDG/kitty/local/wsl.conf" <<'KITTYLOCALEOF'
# Generated by install.sh -- machine-local, not in the repo.
notify_on_cmd_finish unfocused 15.0 command wsl-notify-send.exe --category kitty
KITTYLOCALEOF
            echo "  wrote $XDG/kitty/local/wsl.conf (Windows toast notifications)"
        else
            echo "  wsl-notify-send.exe not on PATH; kitty command-finish notifications disabled"
        fi
    fi
fi

if [ "$IS_WSL" = 1 ]; then
    echo "==> wslg environment"
    # systemd's user manager starts without WSLg's DISPLAY/WAYLAND_DISPLAY, so
    # anything it launches that needs a display dies. dunst is the concrete
    # case: D-Bus activates it, it aborts with "Cannot open X11 display", and
    # every notification call then hangs until it times out.
    #
    # environment.d is read by the systemd user manager at startup, which makes
    # this survive a WSL restart -- unlike `systemctl --user import-environment`,
    # which only affects the running manager.
    ENVD="$XDG/environment.d/wslg.conf"
    mkdir -p "$(dirname "$ENVD")"
    cat > "$ENVD" <<'ENVDEOF'
# Generated by install.sh. WSLg's display sockets, so systemd user units
# (notably dunst) can reach a display. Values are fixed by WSLg.
DISPLAY=:0
WAYLAND_DISPLAY=wayland-0
ENVDEOF
    echo "  wrote $ENVD"
    # Also apply to the manager running right now, so no restart is needed.
    systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR 2>/dev/null || true
fi

echo "==> ccache"
case "$OS" in
    darwin)  link "$DOTFILES/ccache/ccache.conf" "$HOME/Library/Preferences/ccache/ccache.conf" ;;
    *)       link "$DOTFILES/ccache/ccache.conf" "$XDG/ccache/ccache.conf" ;;
esac

echo "==> claude"
link "$DOTFILES/claude/skills"   "$HOME/.claude/skills"
link "$DOTFILES/claude/memory"   "$HOME/.claude/memory"
link "$DOTFILES/claude/CLAUDE.md" "$HOME/.claude/CLAUDE.md"

echo
echo "Done."
if [ "$IS_WSL" = 1 ]; then
    echo "WSL is the source of truth. To refresh the Windows mirror, run"
    echo "install.ps1 from the Windows clone after pulling."
fi
